# See https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.profilers.AdvancedProfiler.html#lightning.pytorch.profilers.AdvancedProfiler
_target_: lightning.pytorch.profilers.AdvancedProfiler
_convert_: "all"

dirpath: ${paths.log_dir}/profiler/advanced/${oc.env:PROJECT_GIT_SHORT_SHA}_${now:%Y-%m-%d_%H-%M-%S}
filename: "profiler_output"
line_count_restriction: 1.0 # float: this can be used to limit the number of functions reported for each action. either an integer (to select a count of lines), or a decimal fraction between 0.0 and 1.0 inclusive (to select a percentage of lines)
dump_stats: false # bool: Whether to save raw profiler results. When True then dirpath must be provided.
