# See https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.profilers.PyTorchProfiler.html
_target_: lightning.pytorch.profilers.PyTorchProfiler
_convert_: "all"

dirpath: ${paths.log_dir}/profiler/pytorch/${oc.env:PROJECT_GIT_SHORT_SHA}_${now:%Y-%m-%d_%H-%M-%S}
filename: "profiler_output"
group_by_input_shapes: false
emit_nvtx: false
export_to_chrome: true
row_limit: 20
sort_by_key: null
record_module_names: true
table_kwargs: null
# keyword arguments for the PyTorch profiler
record_shapes: false
profile_memory: false
with_stack: false
with flops: false
