defaults:
  # enable color logging
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# Output directory
run:
  # directory for a single run
  dir: ${paths.log_dir}/${task_name}/output/${join_string_underscore:${tags}}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  # directory for a queue of sub-runs
  dir: ${paths.log_dir}/${task_name}/output/multiruns/${join_string_underscore:${tags}}/${now:%Y-%m-%d_%H-%M-%S}
