defaults:
  - _self_
  - metric_collections: womd

_target_: src.model.aneva.ANeVALightningModule
_convert_: all

network_cfg:
  map_in_features: ???
  map_hidden_size: 64
  map_num_local_layers: 1
  map_num_global_layers: 3
  map_num_pointnet_layers: 3
  num_map_types: ???
  agent_in_features: ???
  agent_hidden_size: 128
  agent_num_local_layers: 1
  agent_num_attention_layers: 1
  num_agent_types: ???
  num_attention_layers: 3
  rst_features: 64
  rst_emb_dim: 64
  rst_sigma: 1.0
  output_dim: ???
  dropout: 0.1
  step_size: ${dataset.step_size}

optimizer_cfg:
  lr: 0.001
  betas:
    - 0.90
    - 0.95
  weight_decay: 0.01
  warmup_steps: 1000
  max_steps: 100000
  min_lr: 0.000001

kl_cfg:
  base_kl_factor: ???

metric_collections: null
