# path to the project root directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data

# path to log directory
log_dir: ${paths.root_dir}/logs

# path to output directory
output_dir: ${hydra:runtime.output_dir}

# path to working directory
working_dir: ${hydra:runtime.cwd}
