defaults:
  - model_checkpoint # checkpointing
  - rich_model_summary # model summary
  - tqdm_progress_bar # progress bar
  - _self_

# Overrides the default configurations
model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_${oc.env:PROJECT_GIT_SHORT_SHA}"
  monitor: "val/loss"
  mode: "min"
  save_last: true
  auto_insert_metric_name: false

model_summary:
  max_depth: 2
