# @package _global_
defaults:
  - _self_
  - dataset: null
  - model: null
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  # Experiment specific settings
  - experiment: null

# Enforce clean git repository
clean_repo: false

# Job name
task_name: "eval"

# Experiment tags
tags: "dev"

# If true, train the model from scratch
train: false

# If to compile the model for acceleration
compile: false

# Specify the previous checkpoint to resume training
checkpoint: null

# Global seed
seed: 42
